static const uint3 gl_WorkGroupSize = uint3(128u, 1u, 1u);

RWByteAddressBuffer root_buffer_0 : register(u0);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    int _21 = int(gl_GlobalInvocationID.x);
    for (int ii = _21; ii < 262144; )
    {
        uint _56 = uint(((ii & 63) + (((ii >> 6) & 63) << 6)) + (((ii >> 12) & 63) << 12));
        uint _58 = _56 * 12u;
        root_buffer_0.Store(uint(int(30408704u + _58) >> int(2u)) * 4 + 0, uint(0));
        root_buffer_0.Store(uint(int(_58 + 30408708u) >> int(2u)) * 4 + 0, uint(0));
        root_buffer_0.Store(uint(int(_58 + 30408712u) >> int(2u)) * 4 + 0, uint(0));
        uint _79 = _56 * 4u;
        root_buffer_0.Store(uint(int(33554432u + _79) >> int(2u)) * 4 + 0, uint(0));
        root_buffer_0.Store(uint(int(34603008u + _79) >> int(2u)) * 4 + 0, uint(0));
        root_buffer_0.Store(uint(int(35651584u + _79) >> int(2u)) * 4 + 0, uint(0));
        ii += 262144;
        continue;
    }
}

[numthreads(128, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
