static const uint3 gl_WorkGroupSize = uint3(128u, 1u, 1u);

RWByteAddressBuffer root_buffer_0 : register(u0);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    int begin_ = int(gl_GlobalInvocationID.x) + 0;
    int end_ = 262144 + 0;
    for (int ii = begin_; ii < end_; ii += 262144)
    {
        int tmp50 = ii + 0;
        uint tmp42219 = 0u + (uint(0) * 83886116u);
        int tmp50534 = ((tmp50 & 63) + (((tmp50 >> 6) & 63) << 6)) + (((tmp50 >> 12) & 63) << 12);
        uint tmp42225 = (tmp42219 + 30408740u) + (uint(tmp50534) * 12u);
        root_buffer_0.Store(uint(int(tmp42225 + 0u) >> int(2u)) * 4 + 0, uint(asint(0.0f)));
        root_buffer_0.Store(uint(int(tmp42225 + 4u) >> int(2u)) * 4 + 0, uint(asint(0.0f)));
        root_buffer_0.Store(uint(int(tmp42225 + 8u) >> int(2u)) * 4 + 0, uint(asint(0.0f)));
        root_buffer_0.Store(uint(int(((tmp42219 + 33554468u) + (uint(tmp50534) * 4u)) + 0u) >> int(2u)) * 4 + 0, uint(asint(0.0f)));
        root_buffer_0.Store(uint(int(((tmp42219 + 34603044u) + (uint(tmp50534) * 4u)) + 0u) >> int(2u)) * 4 + 0, uint(asint(0.0f)));
        root_buffer_0.Store(uint(int(((tmp42219 + 35651620u) + (uint(tmp50534) * 4u)) + 0u) >> int(2u)) * 4 + 0, uint(asint(0.0f)));
    }
}

[numthreads(128, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
